server:
  port: 9096

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

logging:
  level:
    root: ERROR, INFO
    org.springframework.web: ERROR, INFO
    com.howtodoinjava: DEBUG, INFO
    org.hibernate: ERROR, INFO

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 'st1215'
        platform: mysql
        url: jdbc:mysql://localhost/tikuna?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: false
        hibernate:
            ddl-auto: update
        show-sql: true


